### ISSUE TITLE
Feature request: E notation for numbers

### ISSUE THREAD

**Issue by razetime** [dloscutoff/pip#3]
For example:

`aEb →  a*10^b`

Since there was a note in the code saying you wanted to repurpose the E operator.

**Comment by dloscutoff** [comment]
What I'm currently thinking is to make `E` an alias for `**` (since it gets used pretty often) and add an `EE` operator for `a*10**b`. I can add `EE` anytime, I just have to get around to it.

I'm hesitating a bit on `E`, though, since it's a change that breaks backward compatibility--and breaks it in a way that affects code in the tutorial. Either we'd update the tutorial to use the new if-then-else syntax (I'm thinking `EL` for else), which would make the tutorial diverge from the version on TIO, or we wouldn't update the tutorial, leaving people confused when they see `E` being used as an operator in code golf answers. Do you have any thoughts on the TIO compatibility issue going forward?

**Comment by razetime** [comment]
Making E a different operator does sound hard to include now that you mention it is in the if else structure.

It may be a good idea to host a pip kernel somehwere like repl.it or gitpod, if there is a plan to break backward compatibility, so it's simpler for beginners. It would also help to fix the tutorial, and make updates simpler.

**Comment by dloscutoff** [comment]
The `EE` operator has been added as of version 0.21.05.08.
